
#include "employe.h"
#include <QDebug>
#include <QSet>

namespace {
QString detectEmployeFingerprintColumn(QSqlError* errorOut = nullptr)
{
    if (!QSqlDatabase::database().isOpen()) {
        if (errorOut) *errorOut = QSqlError();
        return QString();
    }

    QSet<QString> existing;
    QSqlQuery qCols;
    qCols.prepare(
        "SELECT COLUMN_NAME "
        "FROM USER_TAB_COLUMNS "
        "WHERE TABLE_NAME = 'EMPLOYE'"
    );
    if (!qCols.exec()) {
        if (errorOut) *errorOut = qCols.lastError();
        return QString();
    }
    while (qCols.next()) {
        existing.insert(qCols.value(0).toString().trimmed().toUpper());
    }

    static const QStringList candidates = {
        QStringLiteral("FINGERID"),
        QStringLiteral("FINGER_ID"),
        QStringLiteral("FINGERPRINT_ID"),
        QStringLiteral("ID_FINGERPRINT"),
        QStringLiteral("EMP_FINGERPRINT_ID"),
        QStringLiteral("EMPREINTE")
    };

    for (const QString& c : candidates) {
        if (existing.contains(c)) return c;
    }
    return QString();
}

void bindFingerprintValue(QSqlQuery& query, const QString& column, const QString& fingerId)
{
    if (column == QStringLiteral("EMPREINTE")) {
        query.bindValue(":finger_id", fingerId.toUtf8());
    } else {
        query.bindValue(":finger_id", fingerId);
    }
}
}

// ──────────────────────────────────────────────────────────────────────────────
// Constructors
// ──────────────────────────────────────────────────────────────────────────────

Employe::Employe()
    : m_idEmp(-1)
    , m_nomEmp()
    , m_prenomEmp()
    , m_email()
    , m_role()
    , m_mdp()
    , m_dateEmbauche()
    , m_photo()
    , m_empreinte()
    , m_modeleFaciale()
    , m_fingerId()
{}

Employe::Employe(int id_emp, const QString& nom_emp, const QString& prenom_emp,
                 const QString& email, const QString& role, const QString& mdp,
                 const QDate& dateEmbauche,
                 const QByteArray& photo, const QByteArray& empreinte,
                 const QByteArray& modeleFaciale,
                 const QString& fingerid)
    : m_idEmp(id_emp)
    , m_nomEmp(nom_emp)
    , m_prenomEmp(prenom_emp)
    , m_email(email)
    , m_role(role)
    , m_mdp(mdp)
    , m_dateEmbauche(dateEmbauche)
    , m_photo(photo)
    , m_empreinte(empreinte)
    , m_modeleFaciale(modeleFaciale)
    , m_fingerId(fingerid)
{}

// ──────────────────────────────────────────────────────────────────────────────
// Getters
// ──────────────────────────────────────────────────────────────────────────────

int        Employe::getIdEmp()         const { return m_idEmp; }
QString    Employe::getNomEmp()        const { return m_nomEmp; }
QString    Employe::getPrenomEmp()     const { return m_prenomEmp; }
QString    Employe::getEmail()         const { return m_email; }
QString    Employe::getRole()          const { return m_role; }
QString    Employe::getMdp()           const { return m_mdp; }
QDate      Employe::getDateEmbauche()  const { return m_dateEmbauche; }
QByteArray Employe::getPhoto()         const { return m_photo; }
QByteArray Employe::getEmpreinte()     const { return m_empreinte; }
QByteArray Employe::getModeleFaciale() const { return m_modeleFaciale; }
QString    Employe::getFingerId()      const { return m_fingerId; }

// ──────────────────────────────────────────────────────────────────────────────
// Setters
// ──────────────────────────────────────────────────────────────────────────────

void Employe::setIdEmp(int id)                       { m_idEmp = id; }
void Employe::setNomEmp(const QString& nom)           { m_nomEmp = nom; }
void Employe::setPrenomEmp(const QString& prenom)     { m_prenomEmp = prenom; }
void Employe::setEmail(const QString& email)          { m_email = email; }
void Employe::setRole(const QString& role)            { m_role = role; }
void Employe::setMdp(const QString& mdp)              { m_mdp = mdp; }
void Employe::setDateEmbauche(const QDate& date)      { m_dateEmbauche = date; }
void Employe::setPhoto(const QByteArray& photo)       { m_photo = photo; }
void Employe::setEmpreinte(const QByteArray& emp)     { m_empreinte = emp; }
void Employe::setModeleFaciale(const QByteArray& m)   { m_modeleFaciale = m; }
void Employe::setFingerId(const QString& fingerId)    { m_fingerId = fingerId; }

QSqlError Employe::lastError() const { return m_lastError; }

// ──────────────────────────────────────────────────────────────────────────────
// CRUD – Ajouter (INSERT)
// id_emp is auto-generated by the Oracle trigger trg_emp via seq_emp.NEXTVAL
// ──────────────────────────────────────────────────────────────────────────────

bool Employe::ajouter()
{
    QSqlQuery query;
    query.prepare(
        "INSERT INTO EMPLOYE "
        "  (nom_emp, prenom_emp, email, role, mdp, photo, modele_faciale) "
        "VALUES "
        "  (:nom_emp, :prenom_emp, :email, :role, :mdp, :photo, :modele_faciale)"
    );
    query.bindValue(":nom_emp",    m_nomEmp);
    query.bindValue(":prenom_emp", m_prenomEmp);
    query.bindValue(":email",      m_email);
    query.bindValue(":role",       m_role);
    query.bindValue(":mdp",        m_mdp);

    if (m_photo.isEmpty())
        query.bindValue(":photo", QVariant(QMetaType(QMetaType::QByteArray)));
    else
        query.bindValue(":photo", m_photo);

    if (m_modeleFaciale.isEmpty())
        query.bindValue(":modele_faciale", QVariant(QMetaType(QMetaType::QByteArray)));
    else
        query.bindValue(":modele_faciale", m_modeleFaciale);

    if (!query.exec()) {
        m_lastError = query.lastError();
        qDebug() << "ajouter() error:" << m_lastError.text()
                 << "| Driver:" << m_lastError.driverText()
                 << "| DB:"     << m_lastError.databaseText();
        return false;
    }
    // Retrieve the auto-generated id_emp assigned by the trigger
    QSqlQuery idQuery;
    if (idQuery.exec("SELECT seq_emp.CURRVAL FROM DUAL") && idQuery.next()) {
        m_idEmp = idQuery.value(0).toInt();
    }
    return true;
}

// ──────────────────────────────────────────────────────────────────────────────
// CRUD – Supprimer (DELETE)
// ──────────────────────────────────────────────────────────────────────────────

bool Employe::supprimer(int id_emp)
{
    QSqlQuery query;
    query.prepare("DELETE FROM EMPLOYE WHERE id_emp = :id_emp");
    query.bindValue(":id_emp", id_emp);
    if (!query.exec()) {
        m_lastError = query.lastError();
        return false;
    }
    return true;
}

// ──────────────────────────────────────────────────────────────────────────────
// CRUD – Modifier (UPDATE)
// ──────────────────────────────────────────────────────────────────────────────

bool Employe::modifier()
{
    QSqlQuery query;

    // If mdp is empty the user left it blank → keep the existing password in DB
    if (m_mdp.isEmpty()) {
        query.prepare(
            "UPDATE EMPLOYE SET "
            "  nom_emp         = :nom_emp, "
            "  prenom_emp      = :prenom_emp, "
            "  email           = :email, "
            "  role            = :role, "
            "  photo           = :photo, "
            "  modele_faciale  = :modele_faciale "
            "WHERE id_emp = :id_emp"
        );
    } else {
        query.prepare(
            "UPDATE EMPLOYE SET "
            "  nom_emp         = :nom_emp, "
            "  prenom_emp      = :prenom_emp, "
            "  email           = :email, "
            "  role            = :role, "
            "  mdp             = :mdp, "
            "  photo           = :photo, "
            "  modele_faciale  = :modele_faciale "
            "WHERE id_emp = :id_emp"
        );
        query.bindValue(":mdp", m_mdp);
    }

    query.bindValue(":nom_emp",    m_nomEmp);
    query.bindValue(":prenom_emp", m_prenomEmp);
    query.bindValue(":email",      m_email);
    query.bindValue(":role",       m_role);

    if (m_photo.isEmpty())
        query.bindValue(":photo", QVariant(QMetaType(QMetaType::QByteArray)));
    else
        query.bindValue(":photo", m_photo);

    if (m_modeleFaciale.isEmpty())
        query.bindValue(":modele_faciale", QVariant(QMetaType(QMetaType::QByteArray)));
    else
        query.bindValue(":modele_faciale", m_modeleFaciale);

    query.bindValue(":id_emp", m_idEmp);

    if (!query.exec()) {
        m_lastError = query.lastError();
        qDebug() << "modifier() error:" << m_lastError.text()
                 << "| Driver:" << m_lastError.driverText()
                 << "| DB:"     << m_lastError.databaseText();
        return false;
    }
    return true;
}

// ──────────────────────────────────────────────────────────────────────────────
// CRUD – Afficher (SELECT ALL)
// BLOBs excluded from display model (binary data not shown in table)
// ──────────────────────────────────────────────────────────────────────────────

QSqlQueryModel* Employe::afficher()
{
    QSqlQueryModel* model = new QSqlQueryModel();
    model->setQuery(
        "SELECT id_emp, nom_emp, prenom_emp, email, role "
        "FROM EMPLOYE "
        "ORDER BY nom_emp, prenom_emp"
    );
    model->setHeaderData(0, Qt::Horizontal, "ID");
    model->setHeaderData(1, Qt::Horizontal, "Nom");
    model->setHeaderData(2, Qt::Horizontal, QStringLiteral("Pr\u00e9nom"));
    model->setHeaderData(3, Qt::Horizontal, "Email");
    model->setHeaderData(4, Qt::Horizontal, QStringLiteral("R\u00f4le"));
    if (model->lastError().isValid()) {
        m_lastError = model->lastError();
    }
    return model;
}

// ──────────────────────────────────────────────────────────────────────────────
// CRUD – Rechercher (SELECT with filter)
// critere: "nom_emp" | "prenom_emp" | "email" | "role" | "date_embauche"
// Also accepts UI comboBox display-label variants
// ──────────────────────────────────────────────────────────────────────────────

QSqlQueryModel* Employe::rechercher(const QString& critere, const QString& valeur)
{
    static const QMap<QString, QString> colonnes = {
        { "nom_emp",                     "nom_emp"    },
        { "prenom_emp",                  "prenom_emp" },
        { "email",                       "email"      },
        { "role",                        "role"       },
        { "Nom",                         "nom_emp"    },
        { QStringLiteral("Pr\u00e9nom"), "prenom_emp" },
        { "Email",                       "email"      },
        { QStringLiteral("R\u00f4le"),   "role"       },
        { "Name",                        "nom_emp"    },
        { "Status",                      "role"       },
    };
    const QString colonne = colonnes.value(critere, "nom_emp");

    QSqlQuery query;
    query.prepare(
        QString("SELECT id_emp, nom_emp, prenom_emp, email, role "
                "FROM EMPLOYE "
                "WHERE UPPER(TO_CHAR(%1)) LIKE UPPER(:val) "
                "ORDER BY nom_emp, prenom_emp").arg(colonne)
    );
    query.bindValue(":val", "%" + valeur + "%");
    query.exec();

    QSqlQueryModel* model = new QSqlQueryModel();
    model->setQuery(std::move(query));
    model->setHeaderData(0, Qt::Horizontal, "ID");
    model->setHeaderData(1, Qt::Horizontal, "Nom");
    model->setHeaderData(2, Qt::Horizontal, QStringLiteral("Pr\u00e9nom"));
    model->setHeaderData(3, Qt::Horizontal, "Email");
    model->setHeaderData(4, Qt::Horizontal, QStringLiteral("R\u00f4le"));
    if (model->lastError().isValid()) {
        m_lastError = model->lastError();
    }
    return model;
}

// ──────────────────────────────────────────────────────────────────────────────
// Authenticate – used by the login button (email + password check)
// Returns the id_emp of the authenticated user, or -1 on failure.
// ──────────────────────────────────────────────────────────────────────────────

int Employe::authenticate(const QString& email, const QString& mdp)
{
    QSqlQuery query;
    query.prepare(
        "SELECT id_emp FROM EMPLOYE "
        "WHERE email = :email AND mdp = :mdp"
    );
    query.bindValue(":email", email);
    query.bindValue(":mdp",   mdp);
    if (query.exec() && query.next()) {
        return query.value(0).toInt();
    }
    m_lastError = query.lastError();
    return -1;
}

bool Employe::existsByFingerId(const QString& fingerId)
{
    if (!QSqlDatabase::database().isOpen()) {
        return false;
    }

    const QString col = detectEmployeFingerprintColumn(&m_lastError);
    if (col.isEmpty()) return false;

    QSqlQuery query;
    if (col == QStringLiteral("EMPREINTE")) {
        query.prepare("SELECT 1 FROM EMPLOYE WHERE EMPREINTE = :finger_id");
    } else {
        query.prepare(QStringLiteral("SELECT 1 FROM EMPLOYE WHERE %1 = :finger_id").arg(col));
    }
    bindFingerprintValue(query, col, fingerId);
    if (!query.exec()) {
        m_lastError = query.lastError();
        return false;
    }
    return query.next();
}

QString Employe::fullNameByFingerId(const QString& fingerId)
{
    if (!QSqlDatabase::database().isOpen()) {
        return QString();
    }

    const QString col = detectEmployeFingerprintColumn(&m_lastError);
    if (col.isEmpty()) return QString();

    QSqlQuery query;
    if (col == QStringLiteral("EMPREINTE")) {
        query.prepare(
            "SELECT TRIM(COALESCE(prenom_emp,'') || ' ' || COALESCE(nom_emp,'')) "
            "FROM EMPLOYE WHERE EMPREINTE = :finger_id"
        );
        query.bindValue(":finger_id", fingerId.toUtf8());
    } else {
        query.prepare(
            QStringLiteral(
                "SELECT TRIM(COALESCE(prenom_emp,'') || ' ' || COALESCE(nom_emp,'')) "
                "FROM EMPLOYE WHERE %1 = :finger_id").arg(col)
        );
    }
    bindFingerprintValue(query, col, fingerId);
    if (!query.exec()) {
        m_lastError = query.lastError();
        return QString();
    }
    if (query.next()) {
        return query.value(0).toString().trimmed();
    }
    return QString();
}

// ──────────────────────────────────────────────────────────────────────────────
// Fingerprint helpers – Model layer convenience methods
// ──────────────────────────────────────────────────────────────────────────────

bool Employe::findByFingerprintId(const QString& fingerId, int &outEmployeeId, QString &outFullName)
{
    outEmployeeId = -1;
    outFullName.clear();

    if (!QSqlDatabase::database().isOpen()) {
        return false;
    }

    const QString col = detectEmployeFingerprintColumn(&m_lastError);
    if (col.isEmpty()) {
        return false;
    }

    QSqlQuery query;
    if (col == QStringLiteral("EMPREINTE")) {
        query.prepare(
            "SELECT id_emp, TRIM(COALESCE(prenom_emp,'') || ' ' || COALESCE(nom_emp,'')) "
            "FROM EMPLOYE WHERE EMPREINTE = :finger_id"
        );
        query.bindValue(":finger_id", fingerId.toUtf8());
    } else {
        query.prepare(
            QStringLiteral(
                "SELECT id_emp, TRIM(COALESCE(prenom_emp,'') || ' ' || COALESCE(nom_emp,'')) "
                "FROM EMPLOYE WHERE %1 = :finger_id").arg(col)
        );
        bindFingerprintValue(query, col, fingerId);
    }

    if (!query.exec()) {
        m_lastError = query.lastError();
        return false;
    }

    if (query.next()) {
        outEmployeeId = query.value(0).toInt();
        outFullName = query.value(1).toString().trimmed();
        return outEmployeeId > 0;
    }

    return false;
}

bool Employe::updateFingerprintId(int employeeId, const QString &fingerprintId)
{
    if (!QSqlDatabase::database().isOpen()) {
        return false;
    }

    const QString col = detectEmployeFingerprintColumn(&m_lastError);
    if (col.isEmpty()) {
        return false;
    }

    QSqlQuery query;
    if (col == QStringLiteral("EMPREINTE")) {
        query.prepare(QStringLiteral("UPDATE EMPLOYE SET EMPREINTE = :finger_id WHERE id_emp = :id"));
        query.bindValue(":finger_id", fingerprintId.toUtf8());
    } else {
        query.prepare(QStringLiteral("UPDATE EMPLOYE SET %1 = :finger_id WHERE id_emp = :id").arg(col));
        query.bindValue(":finger_id", fingerprintId);
    }
    query.bindValue(":id", employeeId);

    if (!query.exec()) {
        m_lastError = query.lastError();
        qDebug() << "updateFingerprintId() error:" << m_lastError.text();
        return false;
    }

    return true;
}
