--------------------------------------------------------
--  Fichier créé - lundi-avril-20-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AGRI
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_AGRI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CITERNE
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_CITERNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMP
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_EMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_HIST
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_HIST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOT
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_LOT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MACHINE
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_MACHINE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERIE
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_SERIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STOCK
--------------------------------------------------------

   CREATE SEQUENCE  "ABDELMAJID"."SEQ_STOCK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AGRICULTEUR
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."AGRICULTEUR" 
   (	"ID_AGRI" NUMBER, 
	"NOM_AGRI" VARCHAR2(50 BYTE), 
	"PRENOM_AGRI" VARCHAR2(50 BYTE), 
	"ADRESSE_AGRI" VARCHAR2(255 BYTE), 
	"NUM_AGRI" VARCHAR2(20 BYTE), 
	"MAIL_AGRI" VARCHAR2(100 BYTE), 
	"REGION_AGRI" VARCHAR2(50 BYTE), 
	"NB_ARBRES" NUMBER, 
	"TYPE_OLIVES" VARCHAR2(50 BYTE), 
	"QTOLIVES_ANNEEPREC" NUMBER, 
	"RENDE_MOY" NUMBER(5,2), 
	"DATE_PREMVISI" DATE, 
	"NOTE_QUALTMOY" NUMBER(5,2), 
	"DATERECOLTE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITERNE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."CITERNE" 
   (	"ID_CITERNE" NUMBER, 
	"CAPACITEMAX" NUMBER, 
	"NIVEAUACTUEL" NUMBER, 
	"TYPEHUILE" VARCHAR2(30 BYTE), 
	"TEMPERATURE_CITERNE" NUMBER(5,2), 
	"ETAT_CITERNE" VARCHAR2(30 BYTE), 
	"ID_LOT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."EMPLOYE" 
   (	"ID_EMP" NUMBER, 
	"NOM_EMP" VARCHAR2(50 BYTE), 
	"PRENOM_EMP" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(30 BYTE), 
	"MDP" VARCHAR2(255 BYTE), 
	"PHOTO" BLOB, 
	"EMPREINTE" BLOB, 
	"MODELE_FACIALE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMPREINTE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MODELE_FACIALE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMP_MACH
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."EMP_MACH" 
   (	"ID_SERIE" NUMBER, 
	"ID_EMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."HISTORIQUE" 
   (	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE_OLIVES
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."HISTORIQUE_OLIVES" 
   (	"ID_HIST" NUMBER, 
	"ID_AGRI" NUMBER, 
	"ANNEE" NUMBER, 
	"NB_ARBRES" NUMBER, 
	"TYPE_OLIVES" VARCHAR2(50 BYTE), 
	"QUANTITE" NUMBER, 
	"NOTE" NUMBER, 
	"DATERECOLTE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."MACHINE" 
   (	"ID_MACHINE" NUMBER, 
	"NOM_MACHINE" VARCHAR2(50 BYTE), 
	"TYPE_MACHINE" VARCHAR2(50 BYTE), 
	"ETAT_MACHINE" VARCHAR2(30 BYTE), 
	"DATE_INSTALLATION" DATE, 
	"HEURES_FONCTIONNEMENT" NUMBER DEFAULT 0, 
	"TEMPERATURE_ACTUELLE" NUMBER(5,2), 
	"ID_SERIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUALITE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."QUALITE" 
   (	"ID_LOT" NUMBER, 
	"DATE_PRODUCTION" DATE, 
	"QUANTITE_PRODUITE" NUMBER, 
	"TEMPERATURE_PRODUCTION" NUMBER(5,2), 
	"PH" NUMBER(4,2), 
	"ACIDITE" NUMBER(4,2), 
	"AMERTURE" NUMBER(4,2), 
	"SCORE" NUMBER(5,2), 
	"CODE_COULEUR" VARCHAR2(20 BYTE), 
	"STATUT_QUALITE" VARCHAR2(30 BYTE), 
	"RESPONSABLE_CONTROLE" VARCHAR2(100 BYTE), 
	"MAX_QUANTITE" NUMBER, 
	"ID_STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERIE_MACHINE
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."SERIE_MACHINE" 
   (	"ID_SERIE" NUMBER, 
	"NOM_SERIE" VARCHAR2(50 BYTE), 
	"CAPACITE_PRODUCTION" NUMBER, 
	"DATE_MISE_SERVICE" DATE, 
	"ETAT_SERIE" VARCHAR2(30 BYTE), 
	"RESPONSABLE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "ABDELMAJID"."STOCK" 
   (	"ID_STOCK" NUMBER, 
	"NOM_STOCK" VARCHAR2(50 BYTE), 
	"CATEG_STOCK" VARCHAR2(30 BYTE), 
	"DATEAJT_STOCK" DATE DEFAULT SYSDATE, 
	"DESCRIPT_STOCK" VARCHAR2(255 BYTE), 
	"DATEMAJ_STOCK" DATE, 
	"QT_STOCK" NUMBER, 
	"ID_AGRI" NUMBER, 
	"ID_SERIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ABDELMAJID.AGRICULTEUR
SET DEFINE OFF;
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('10','slim','monji','tataoui','24467876','TGHJIOIUYT5T@gmail.com ','gabes',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('84','u','u','u','55666999','u@','u','240','sahel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('3','midou','zer','ez','1','-(''"é','dfghj','7','zer',null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('25','RANINETTE ','madalina','GABES','21621626','akejej@gmail.com','MEDNIN',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('26','rayen','fathi ','kairouan','55333666','aaayya@gmail.com','annaba',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('41','midou ','bhim ','gabes','32111222','hsh@gmail.com','tataouin ',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('65','eeeeeeeeeez','zzzzzzzzzzzzzzzzzzzzzzzz','lllllllllllll','11222333','a@a','aaaaaaaaaaaa',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('85','i','i','i','11222333','i@','i','125','chamel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('68','loulou ','boubi','awwwwwwwww','44333555','lalalla@','waaaaaaaaaa',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('69','z','z','a','99888777','z@','z',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('70','salem','alaykom','nabeul','22333676','AA@H','zarzis',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('71','zizou','eeeeee','rrrrrrrrrrr','11222333','1@','xxxxxxxxxxx',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('20','slim','monji','tataoui','24467876','TGHJIOIUYT5T@gmail.com ','gabes',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('21','slim','monji','tataoui','24467876','TGHJIOIUYT5T@gmail.com ','gabes',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('72','A','A','A','22333444','A@','A','2','sahel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('73','m','m','m','22111333','m@','m',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('24','monji ','fathi ','fel eSPRIT','12212121','gabes@gmail.com','toronto',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('74','f','fifaaaa','f','99333999','f@','f',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('86','F','F','F','21333444','F@','F','150','sahel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('76','l','l','L','44999222','LL@','L','950','chamel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('78','k','k','k','11111111','k@','k',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('80','s','s','S','22333999','S@','s',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('81','j','j','J','11222555','J@','J',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('82','v','v','v','4321234322','v@v','v',null,null,null,null,null,null,null);
Insert into ABDELMAJID.AGRICULTEUR (ID_AGRI,NOM_AGRI,PRENOM_AGRI,ADRESSE_AGRI,NUM_AGRI,MAIL_AGRI,REGION_AGRI,NB_ARBRES,TYPE_OLIVES,QTOLIVES_ANNEEPREC,RENDE_MOY,DATE_PREMVISI,NOTE_QUALTMOY,DATERECOLTE) values ('83','p','p','P','44555777','P@','p','67','sahel',null,null,null,null,to_date('20/04/26','DD/MM/RR'));
REM INSERTING into ABDELMAJID.CITERNE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.EMPLOYE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.EMP_MACH
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.HISTORIQUE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.HISTORIQUE_OLIVES
SET DEFINE OFF;
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('37','86','2026','150','sahel','400','8,39999962',to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('23','3','2026','9','sahel','1111','9,5',to_date('02/02/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('25','21','2026','5','chamel','55','9,10000038',to_date('01/11/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('33','72','2026','2','sahel','7','2',to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('36','85','2026','125','chamel','670','8',to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('32','76','2026','950','chamel','9999','9',to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('34','83','2026','67','sahel','199','5,9000001',to_date('20/04/26','DD/MM/RR'));
Insert into ABDELMAJID.HISTORIQUE_OLIVES (ID_HIST,ID_AGRI,ANNEE,NB_ARBRES,TYPE_OLIVES,QUANTITE,NOTE,DATERECOLTE) values ('35','84','2026','240','sahel','400','7,0999999',to_date('20/04/26','DD/MM/RR'));
REM INSERTING into ABDELMAJID.MACHINE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.QUALITE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.SERIE_MACHINE
SET DEFINE OFF;
REM INSERTING into ABDELMAJID.STOCK
SET DEFINE OFF;
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('73','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'400','86',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('43','Stock Olives','Olives',to_date('19/04/26','DD/MM/RR'),'Ajout depuis historique',to_date('19/04/26','DD/MM/RR'),'1111','3',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('45','Stock Olives','Olives',to_date('19/04/26','DD/MM/RR'),'Ajout depuis historique',to_date('19/04/26','DD/MM/RR'),'55','21',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('63','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'9999','76',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('65','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'7','72',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('57','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'6767','76',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('59','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'6767','76',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('61','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'9999','76',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('67','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'199','83',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('69','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'400','84',null);
Insert into ABDELMAJID.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values ('71','Stock Olives','Olives',to_date('20/04/26','DD/MM/RR'),'Ajout',to_date('20/04/26','DD/MM/RR'),'670','85',null);
--------------------------------------------------------
--  DDL for Index PK_MACHINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_MACHINE" ON "ABDELMAJID"."MACHINE" ("ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CITERNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_CITERNE" ON "ABDELMAJID"."CITERNE" ("ID_CITERNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_QUALITE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_QUALITE" ON "ABDELMAJID"."QUALITE" ("ID_LOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_EMPLOYE" ON "ABDELMAJID"."EMPLOYE" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AGRICULTEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_AGRICULTEUR" ON "ABDELMAJID"."AGRICULTEUR" ("ID_AGRI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_EMPLOYE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."UQ_EMPLOYE_EMAIL" ON "ABDELMAJID"."EMPLOYE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_STOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_STOCK" ON "ABDELMAJID"."STOCK" ("ID_STOCK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SERIE_MACHINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_SERIE_MACHINE" ON "ABDELMAJID"."SERIE_MACHINE" ("ID_SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMP_MACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDELMAJID"."PK_EMP_MACH" ON "ABDELMAJID"."EMP_MACH" ("ID_SERIE", "ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AGRI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_AGRI" 
BEFORE INSERT ON AGRICULTEUR
FOR EACH ROW
BEGIN
    :NEW.id_agri := seq_agri.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_AGRI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CITERNE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_CITERNE" 
BEFORE INSERT ON CITERNE
FOR EACH ROW
BEGIN
    :NEW.id_citerne := seq_citerne.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_CITERNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_EMP" 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
BEGIN
    :NEW.id_emp := seq_emp.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_EMP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_HIST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_HIST" 
BEFORE INSERT ON HISTORIQUE_OLIVES
FOR EACH ROW
BEGIN
    :NEW.ID_HIST := seq_hist.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_HIST" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LOT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_LOT" 
BEFORE INSERT ON QUALITE
FOR EACH ROW
BEGIN
    :NEW.id_lot := seq_lot.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_LOT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MACHINE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_MACHINE" 
BEFORE INSERT ON MACHINE
FOR EACH ROW
BEGIN
    :NEW.id_machine := seq_machine.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_MACHINE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERIE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_SERIE" 
BEFORE INSERT ON SERIE_MACHINE
FOR EACH ROW
BEGIN
    :NEW.id_serie := seq_serie.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_SERIE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STOCK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDELMAJID"."TRG_STOCK" 
BEFORE INSERT ON STOCK
FOR EACH ROW
BEGIN
    :NEW.id_stock := seq_stock.NEXTVAL;
END;

/
ALTER TRIGGER "ABDELMAJID"."TRG_STOCK" ENABLE;
--------------------------------------------------------
--  Constraints for Table CITERNE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."CITERNE" ADD CONSTRAINT "PK_CITERNE" PRIMARY KEY ("ID_CITERNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."CITERNE" MODIFY ("CAPACITEMAX" CONSTRAINT "NN_CITERNE_CAP" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."CITERNE" MODIFY ("ID_CITERNE" CONSTRAINT "NN_CITERNE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY ("ID_STOCK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."STOCK" MODIFY ("ID_STOCK" CONSTRAINT "NN_STOCK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."QUALITE" ADD CONSTRAINT "PK_QUALITE" PRIMARY KEY ("ID_LOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."QUALITE" MODIFY ("ID_LOT" CONSTRAINT "NN_QUALITE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP_MACH
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."EMP_MACH" ADD CONSTRAINT "PK_EMP_MACH" PRIMARY KEY ("ID_SERIE", "ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."EMP_MACH" MODIFY ("ID_EMP" CONSTRAINT "NN_EMPMACH_EMP" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMP_MACH" MODIFY ("ID_SERIE" CONSTRAINT "NN_EMPMACH_SERIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIQUE_OLIVES
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."HISTORIQUE_OLIVES" ADD PRIMARY KEY ("ID_HIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGRICULTEUR
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."AGRICULTEUR" ADD CONSTRAINT "PK_AGRICULTEUR" PRIMARY KEY ("ID_AGRI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."AGRICULTEUR" MODIFY ("NOM_AGRI" CONSTRAINT "NN_AGRI_NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."AGRICULTEUR" MODIFY ("ID_AGRI" CONSTRAINT "NN_AGRI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."EMPLOYE" ADD CONSTRAINT "UQ_EMPLOYE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("MDP" CONSTRAINT "NN_EMPLOYE_MDP" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("ROLE" CONSTRAINT "NN_EMPLOYE_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("EMAIL" CONSTRAINT "NN_EMPLOYE_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("PRENOM_EMP" CONSTRAINT "NN_EMPLOYE_PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("NOM_EMP" CONSTRAINT "NN_EMPLOYE_NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."EMPLOYE" MODIFY ("ID_EMP" CONSTRAINT "NN_EMPLOYE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERIE_MACHINE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."SERIE_MACHINE" ADD CONSTRAINT "PK_SERIE_MACHINE" PRIMARY KEY ("ID_SERIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."SERIE_MACHINE" MODIFY ("CAPACITE_PRODUCTION" CONSTRAINT "NN_SERIE_CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."SERIE_MACHINE" MODIFY ("NOM_SERIE" CONSTRAINT "NN_SERIE_NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."SERIE_MACHINE" MODIFY ("ID_SERIE" CONSTRAINT "NN_SERIE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."MACHINE" ADD CONSTRAINT "PK_MACHINE" PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDELMAJID"."MACHINE" MODIFY ("ID_SERIE" CONSTRAINT "NN_MACHINE_SERIE" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."MACHINE" MODIFY ("NOM_MACHINE" CONSTRAINT "NN_MACHINE_NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDELMAJID"."MACHINE" MODIFY ("ID_MACHINE" CONSTRAINT "NN_MACHINE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CITERNE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."CITERNE" ADD CONSTRAINT "FK_CITERNE_LOT" FOREIGN KEY ("ID_LOT")
	  REFERENCES "ABDELMAJID"."QUALITE" ("ID_LOT") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP_MACH
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."EMP_MACH" ADD CONSTRAINT "FK_EMP_MACH_EMP" FOREIGN KEY ("ID_EMP")
	  REFERENCES "ABDELMAJID"."EMPLOYE" ("ID_EMP") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ABDELMAJID"."EMP_MACH" ADD CONSTRAINT "FK_EMP_MACH_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "ABDELMAJID"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIQUE_OLIVES
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."HISTORIQUE_OLIVES" ADD CONSTRAINT "FK_HIST_AGRI" FOREIGN KEY ("ID_AGRI")
	  REFERENCES "ABDELMAJID"."AGRICULTEUR" ("ID_AGRI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."MACHINE" ADD CONSTRAINT "FK_MACHINE_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "ABDELMAJID"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITE
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."QUALITE" ADD CONSTRAINT "FK_QUALITE_STOCK" FOREIGN KEY ("ID_STOCK")
	  REFERENCES "ABDELMAJID"."STOCK" ("ID_STOCK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "ABDELMAJID"."STOCK" ADD CONSTRAINT "FK_STOCK_AGRI" FOREIGN KEY ("ID_AGRI")
	  REFERENCES "ABDELMAJID"."AGRICULTEUR" ("ID_AGRI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ABDELMAJID"."STOCK" ADD CONSTRAINT "FK_STOCK_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "ABDELMAJID"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
