
CREATE SEQUENCE seq_hist START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_HIST
BEFORE INSERT ON HISTORIQUE_OLIVES
FOR EACH ROW
BEGIN
    :NEW.ID_HIST := seq_hist.NEXTVAL;
END;
/
ALTER TABLE HISTORIQUE_OLIVES ADD DATERECOLTE DATE;
