--------------------------------------------------------
--  Fichier cr�� - mardi-mars-31-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AGRI
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_AGRI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CITERNE
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_CITERNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMP
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_EMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMP_MACH_AFF
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_EMP_MACH_AFF"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOT
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_LOT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MACHINE
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_MACHINE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERIE
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_SERIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STOCK
--------------------------------------------------------

   CREATE SEQUENCE  "SOUHAIL"."SEQ_STOCK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AGRICULTEUR
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."AGRICULTEUR" 
   (	"ID_AGRI" NUMBER, 
	"NOM_AGRI" VARCHAR2(50 BYTE), 
	"PRENOM_AGRI" VARCHAR2(50 BYTE), 
	"ADRESSE_AGRI" VARCHAR2(255 BYTE), 
	"NUM_AGRI" VARCHAR2(20 BYTE), 
	"MAIL_AGRI" VARCHAR2(100 BYTE), 
	"REGION_AGRI" VARCHAR2(50 BYTE), 
	"NB_ARBRES" NUMBER, 
	"TYPE_OLIVES" VARCHAR2(50 BYTE), 
	"QTOLIVES_ANNEEPREC" NUMBER, 
	"RENDE_MOY" NUMBER(5,2), 
	"DATE_PREMVISI" DATE, 
	"NOTE_QUALTMOY" NUMBER(5,2), 
	"DATERECOLTE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITERNE
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."CITERNE" 
   (	"ID_CITERNE" NUMBER, 
	"CAPACITEMAX" NUMBER, 
	"NIVEAUACTUEL" NUMBER, 
	"TYPEHUILE" VARCHAR2(30 BYTE), 
	"TEMPERATURE_CITERNE" NUMBER(5,2), 
	"ETAT_CITERNE" VARCHAR2(30 BYTE), 
	"ID_LOT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."EMPLOYE" 
   (	"ID_EMP" NUMBER, 
	"NOM_EMP" VARCHAR2(50 BYTE), 
	"PRENOM_EMP" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(30 BYTE), 
	"MDP" VARCHAR2(255 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"PHOTO" BLOB, 
	"EMPREINTE" BLOB, 
	"MODELE_FACIALE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMPREINTE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MODELE_FACIALE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMP_MACH
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."EMP_MACH" 
   (	"ID_SERIE" NUMBER, 
	"ID_EMP" NUMBER, 
	"POSTE" VARCHAR2(50 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"ID_AFFECTATION" NUMBER, 
	"ETAT_AFFECTATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."MACHINE" 
   (	"ID_MACHINE" NUMBER, 
	"NOM_MACHINE" VARCHAR2(50 BYTE), 
	"TYPE_MACHINE" VARCHAR2(50 BYTE), 
	"ETAT_MACHINE" VARCHAR2(30 BYTE), 
	"DATE_INSTALLATION" DATE, 
	"HEURES_FONCTIONNEMENT" NUMBER DEFAULT 0, 
	"TEMPERATURE_ACTUELLE" NUMBER(5,2), 
	"ID_SERIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUALITE
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."QUALITE" 
   (	"ID_LOT" NUMBER, 
	"DATE_PRODUCTION" DATE, 
	"QUANTITE_PRODUITE" NUMBER, 
	"TEMPERATURE_PRODUCTION" NUMBER(5,2), 
	"PH" NUMBER(4,2), 
	"ACIDITE" NUMBER(4,2), 
	"AMERTURE" NUMBER(4,2), 
	"SCORE" NUMBER(5,2), 
	"CODE_COULEUR" VARCHAR2(20 BYTE), 
	"STATUT_QUALITE" VARCHAR2(30 BYTE), 
	"RESPONSABLE_CONTROLE" VARCHAR2(100 BYTE), 
	"MAX_QUANTITE" NUMBER, 
	"ID_STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERIE_MACHINE
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."SERIE_MACHINE" 
   (	"ID_SERIE" NUMBER, 
	"NOM_SERIE" VARCHAR2(50 BYTE), 
	"CAPACITE_PRODUCTION" NUMBER, 
	"DATE_MISE_SERVICE" DATE, 
	"ETAT_SERIE" VARCHAR2(30 BYTE), 
	"RESPONSABLE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "SOUHAIL"."STOCK" 
   (	"ID_STOCK" NUMBER, 
	"NOM_STOCK" VARCHAR2(50 BYTE), 
	"CATEG_STOCK" VARCHAR2(30 BYTE), 
	"DATEAJT_STOCK" DATE DEFAULT SYSDATE, 
	"DESCRIPT_STOCK" VARCHAR2(255 BYTE), 
	"DATEMAJ_STOCK" DATE, 
	"QT_STOCK" NUMBER, 
	"ID_AGRI" NUMBER, 
	"ID_SERIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOUHAIL.AGRICULTEUR
SET DEFINE OFF;
REM INSERTING into SOUHAIL.CITERNE
SET DEFINE OFF;
REM INSERTING into SOUHAIL.EMPLOYE
SET DEFINE OFF;
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (1,'kkkkkkhhh','slsl','ssss@@Slsl.sl','Operateur','spps',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (41,'Ben Ali','Mohamed','mohamed.benali@smartoil.tn','Administrateur','Admin@1234',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (42,'Trabelsi','Sarra','sarra.trabelsi@smartoil.tn','Manager','Manager@1234',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (43,'Chahed','Yassine','yassine.chahed@smartoil.tn','Technicien','Tech@1234',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (44,'Mansouri','Rania','rania.mansouri@smartoil.tn','Operateur','Oper@1234',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (45,'Ferchichi','Khaled','khaled.ferchichi@smartoil.tn','Technicien','Tech@5678',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (46,'Bouzid','Amira','amira.bouzid@smartoil.tn','Operateur','Oper@5678',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (47,'Jebali','Hichem','hichem.jebali@smartoil.tn','Manager','Manager@5678',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (48,'Riahi','Nour','nour.riahi@smartoil.tn','Technicien','Tech@9012',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (49,'Hamdi','Anas','anas.hamdi@smartoil.tn','Operateur','Oper@9012',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (50,'Ayari','Fatma','fatma.ayari@smartoil.tn','Operateur','Tech@3456',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (51,'kjlj','f,lkf','ddl@dd3.d','Operateur','ddd',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (52,'souhail','serghine','sou.sergh@outlook.fr','Technicien','1234',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (53,'skk','lflf','ldlzz','Technicien','sljls',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (54,'HAMMA','BARRAK','hamma.barrak@dkd.com','Technicien','smlsplz',null);
Insert into SOUHAIL.EMPLOYE (ID_EMP,NOM_EMP,PRENOM_EMP,EMAIL,ROLE,MDP,DATE_EMBAUCHE) values (55,'imen','lassoued','imen@esprit.tn','Manager','eiudhej',null);
REM INSERTING into SOUHAIL.EMP_MACH
SET DEFINE OFF;
Insert into SOUHAIL.EMP_MACH (ID_SERIE,ID_EMP,POSTE,DATE_DEBUT,DATE_FIN,ID_AFFECTATION,ETAT_AFFECTATION) values (1,50,'Op�rateur',to_date('01-03-26','DD-MM-RR'),null,1,'ACTIVE');
Insert into SOUHAIL.EMP_MACH (ID_SERIE,ID_EMP,POSTE,DATE_DEBUT,DATE_FIN,ID_AFFECTATION,ETAT_AFFECTATION) values (7,43,'Technicien',to_date('03-03-26','DD-MM-RR'),to_date('03-04-26','DD-MM-RR'),2,'TERMINEE');
Insert into SOUHAIL.EMP_MACH (ID_SERIE,ID_EMP,POSTE,DATE_DEBUT,DATE_FIN,ID_AFFECTATION,ETAT_AFFECTATION) values (6,43,null,null,null,3,'ACTIVE');
Insert into SOUHAIL.EMP_MACH (ID_SERIE,ID_EMP,POSTE,DATE_DEBUT,DATE_FIN,ID_AFFECTATION,ETAT_AFFECTATION) values (3,1,null,null,null,4,'ACTIVE');
REM INSERTING into SOUHAIL.MACHINE
SET DEFINE OFF;
Insert into SOUHAIL.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATE_INSTALLATION,HEURES_FONCTIONNEMENT,TEMPERATURE_ACTUELLE,ID_SERIE) values (5,'Presse Hydraulique A','Presse','En service',to_date('15-03-21','DD-MM-RR'),1420,45,1);
Insert into SOUHAIL.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATE_INSTALLATION,HEURES_FONCTIONNEMENT,TEMPERATURE_ACTUELLE,ID_SERIE) values (6,'Presse Hydraulique B','Presse','En service',to_date('15-03-21','DD-MM-RR'),1380,43,3);
Insert into SOUHAIL.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATE_INSTALLATION,HEURES_FONCTIONNEMENT,TEMPERATURE_ACTUELLE,ID_SERIE) values (7,'Decanteur Central','Decanteur','En service',to_date('10-09-20','DD-MM-RR'),2100,38,5);
Insert into SOUHAIL.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATE_INSTALLATION,HEURES_FONCTIONNEMENT,TEMPERATURE_ACTUELLE,ID_SERIE) values (8,'Separateur Centrifuge','Separateur','Maintenance',to_date('20-01-22','DD-MM-RR'),860,55,7);
REM INSERTING into SOUHAIL.QUALITE
SET DEFINE OFF;
REM INSERTING into SOUHAIL.SERIE_MACHINE
SET DEFINE OFF;
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (1,'Série A1',500,to_date('15-03-21','DD-MM-RR'),'Active','Ahmed Benali','Première série de la presse A – olives vertes');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (2,'Série A2',480,to_date('01-06-21','DD-MM-RR'),'Active','Ahmed Benali','Deuxième série de la presse A – olives noires');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (3,'Série B1',520,to_date('15-03-21','DD-MM-RR'),'Active','Karim Mansouri','Première série de la presse B – haut rendement');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (4,'Série B2',490,to_date('10-02-22','DD-MM-RR'),'Inactive','Karim Mansouri','Deuxième série de la presse B – en veille');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (5,'Série D1',800,to_date('10-09-20','DD-MM-RR'),'Active','Fatima Zahra','Série principale du décanteur – 3 phases');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (6,'Série D2',750,to_date('15-01-21','DD-MM-RR'),'Active','Fatima Zahra','Série secondaire du décanteur – 2 phases');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (7,'Série S1',300,to_date('20-01-22','DD-MM-RR'),'Active','Youssef Driss','Série haute vitesse du séparateur');
Insert into SOUHAIL.SERIE_MACHINE (ID_SERIE,NOM_SERIE,CAPACITE_PRODUCTION,DATE_MISE_SERVICE,ETAT_SERIE,RESPONSABLE,DESCRIPTION) values (8,'Série S2',280,to_date('05-05-22','DD-MM-RR'),'Maintenance','Youssef Driss','Série en maintenance planifiée');
REM INSERTING into SOUHAIL.STOCK
SET DEFINE OFF;
Insert into SOUHAIL.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values (1,'dndn','Vert',to_date('01-01-10','DD-MM-RR'),'denle,',null,55,null,6);
Insert into SOUHAIL.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values (2,'sllsjl','Vert',to_date('27-03-26','DD-MM-RR'),'5646',null,55,null,1);
Insert into SOUHAIL.STOCK (ID_STOCK,NOM_STOCK,CATEG_STOCK,DATEAJT_STOCK,DESCRIPT_STOCK,DATEMAJ_STOCK,QT_STOCK,ID_AGRI,ID_SERIE) values (3,'kfkfk','M�lange',to_date('05-02-25','DD-MM-RR'),'51113ddd',null,5665,null,3);
--------------------------------------------------------
--  DDL for Index IDX_EMP_MACH_EMP_SERIE
--------------------------------------------------------

  CREATE INDEX "SOUHAIL"."IDX_EMP_MACH_EMP_SERIE" ON "SOUHAIL"."EMP_MACH" ("ID_EMP", "ID_SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_EMP_MACH_ETAT
--------------------------------------------------------

  CREATE INDEX "SOUHAIL"."IDX_EMP_MACH_ETAT" ON "SOUHAIL"."EMP_MACH" ("ETAT_AFFECTATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AGRICULTEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_AGRICULTEUR" ON "SOUHAIL"."AGRICULTEUR" ("ID_AGRI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CITERNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_CITERNE" ON "SOUHAIL"."CITERNE" ("ID_CITERNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_EMPLOYE" ON "SOUHAIL"."EMPLOYE" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMP_MACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_EMP_MACH" ON "SOUHAIL"."EMP_MACH" ("ID_AFFECTATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MACHINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_MACHINE" ON "SOUHAIL"."MACHINE" ("ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_QUALITE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_QUALITE" ON "SOUHAIL"."QUALITE" ("ID_LOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SERIE_MACHINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_SERIE_MACHINE" ON "SOUHAIL"."SERIE_MACHINE" ("ID_SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_STOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."PK_STOCK" ON "SOUHAIL"."STOCK" ("ID_STOCK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_EMP_MACH_ACTIVE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."UK_EMP_MACH_ACTIVE" ON "SOUHAIL"."EMP_MACH" (CASE "ETAT_AFFECTATION" WHEN 'ACTIVE' THEN "ID_EMP" END , CASE "ETAT_AFFECTATION" WHEN 'ACTIVE' THEN "ID_SERIE" END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_EMPLOYE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUHAIL"."UQ_EMPLOYE_EMAIL" ON "SOUHAIL"."EMPLOYE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AGRI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_AGRI" 
BEFORE INSERT ON AGRICULTEUR
FOR EACH ROW
BEGIN
    :NEW.id_agri := seq_agri.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_AGRI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CITERNE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_CITERNE" 
BEFORE INSERT ON CITERNE
FOR EACH ROW
BEGIN
    :NEW.id_citerne := seq_citerne.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_CITERNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_EMP" 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
BEGIN
    :NEW.id_emp := seq_emp.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_EMP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMP_MACH_BIU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_EMP_MACH_BIU" 
BEFORE INSERT OR UPDATE OF DATE_FIN, DATE_DEBUT ON SOUHAIL.EMP_MACH
FOR EACH ROW
BEGIN
  -- auto PK on insert
  IF INSERTING AND :NEW.ID_AFFECTATION IS NULL THEN
    :NEW.ID_AFFECTATION := SOUHAIL.SEQ_EMP_MACH_AFF.NEXTVAL;
  END IF;

  -- auto status from DATE_FIN
  IF :NEW.DATE_FIN IS NULL THEN
    :NEW.ETAT_AFFECTATION := 'ACTIVE';
  ELSE
    :NEW.ETAT_AFFECTATION := 'TERMINEE';
  END IF;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_EMP_MACH_BIU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LOT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_LOT" 
BEFORE INSERT ON QUALITE
FOR EACH ROW
BEGIN
    :NEW.id_lot := seq_lot.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_LOT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MACHINE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_MACHINE" 
BEFORE INSERT ON MACHINE
FOR EACH ROW
BEGIN
    :NEW.id_machine := seq_machine.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_MACHINE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERIE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_SERIE" 
BEFORE INSERT ON SERIE_MACHINE
FOR EACH ROW
BEGIN
    :NEW.id_serie := seq_serie.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_SERIE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STOCK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUHAIL"."TRG_STOCK" 
BEFORE INSERT ON STOCK
FOR EACH ROW
BEGIN
    :NEW.id_stock := seq_stock.NEXTVAL;
END;

/
ALTER TRIGGER "SOUHAIL"."TRG_STOCK" ENABLE;
--------------------------------------------------------
--  Constraints for Table AGRICULTEUR
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."AGRICULTEUR" ADD CONSTRAINT "PK_AGRICULTEUR" PRIMARY KEY ("ID_AGRI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."AGRICULTEUR" MODIFY ("NOM_AGRI" CONSTRAINT "NN_AGRI_NOM" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."AGRICULTEUR" MODIFY ("ID_AGRI" CONSTRAINT "NN_AGRI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITERNE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."CITERNE" ADD CONSTRAINT "PK_CITERNE" PRIMARY KEY ("ID_CITERNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."CITERNE" MODIFY ("CAPACITEMAX" CONSTRAINT "NN_CITERNE_CAP" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."CITERNE" MODIFY ("ID_CITERNE" CONSTRAINT "NN_CITERNE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."EMPLOYE" ADD CONSTRAINT "UQ_EMPLOYE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."EMPLOYE" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMPLOYE" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMPLOYE" MODIFY ("PRENOM_EMP" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMPLOYE" MODIFY ("NOM_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP_MACH
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."EMP_MACH" ADD CONSTRAINT "CK_EMP_MACH_ETAT" CHECK (ETAT_AFFECTATION IN ('ACTIVE','TERMINEE')) ENABLE;
  ALTER TABLE "SOUHAIL"."EMP_MACH" ADD CONSTRAINT "CK_EMP_MACH_DATES" CHECK (DATE_FIN IS NULL OR DATE_DEBUT IS NULL OR DATE_FIN >= DATE_DEBUT) ENABLE;
  ALTER TABLE "SOUHAIL"."EMP_MACH" MODIFY ("ETAT_AFFECTATION" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMP_MACH" MODIFY ("ID_AFFECTATION" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMP_MACH" ADD CONSTRAINT "PK_EMP_MACH" PRIMARY KEY ("ID_AFFECTATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."EMP_MACH" MODIFY ("ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."EMP_MACH" MODIFY ("ID_SERIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."MACHINE" ADD CONSTRAINT "PK_MACHINE" PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."MACHINE" MODIFY ("ID_SERIE" CONSTRAINT "NN_MACHINE_SERIE" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."MACHINE" MODIFY ("NOM_MACHINE" CONSTRAINT "NN_MACHINE_NOM" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."MACHINE" MODIFY ("ID_MACHINE" CONSTRAINT "NN_MACHINE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."QUALITE" ADD CONSTRAINT "PK_QUALITE" PRIMARY KEY ("ID_LOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."QUALITE" MODIFY ("ID_LOT" CONSTRAINT "NN_QUALITE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERIE_MACHINE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."SERIE_MACHINE" ADD CONSTRAINT "PK_SERIE_MACHINE" PRIMARY KEY ("ID_SERIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."SERIE_MACHINE" MODIFY ("CAPACITE_PRODUCTION" CONSTRAINT "NN_SERIE_CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."SERIE_MACHINE" MODIFY ("NOM_SERIE" CONSTRAINT "NN_SERIE_NOM" NOT NULL ENABLE);
  ALTER TABLE "SOUHAIL"."SERIE_MACHINE" MODIFY ("ID_SERIE" CONSTRAINT "NN_SERIE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY ("ID_STOCK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUHAIL"."STOCK" MODIFY ("ID_STOCK" CONSTRAINT "NN_STOCK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CITERNE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."CITERNE" ADD CONSTRAINT "FK_CITERNE_LOT" FOREIGN KEY ("ID_LOT")
	  REFERENCES "SOUHAIL"."QUALITE" ("ID_LOT") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP_MACH
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."EMP_MACH" ADD CONSTRAINT "FK_EMP_MACH_EMP" FOREIGN KEY ("ID_EMP")
	  REFERENCES "SOUHAIL"."EMPLOYE" ("ID_EMP") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SOUHAIL"."EMP_MACH" ADD CONSTRAINT "FK_EMP_MACH_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "SOUHAIL"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."MACHINE" ADD CONSTRAINT "FK_MACHINE_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "SOUHAIL"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITE
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."QUALITE" ADD CONSTRAINT "FK_QUALITE_STOCK" FOREIGN KEY ("ID_STOCK")
	  REFERENCES "SOUHAIL"."STOCK" ("ID_STOCK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "SOUHAIL"."STOCK" ADD CONSTRAINT "FK_STOCK_AGRI" FOREIGN KEY ("ID_AGRI")
	  REFERENCES "SOUHAIL"."AGRICULTEUR" ("ID_AGRI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SOUHAIL"."STOCK" ADD CONSTRAINT "FK_STOCK_SERIE" FOREIGN KEY ("ID_SERIE")
	  REFERENCES "SOUHAIL"."SERIE_MACHINE" ("ID_SERIE") ON DELETE CASCADE ENABLE;
